#!/bin/sh
# Create tce/tcz from Debian package
# Usage: $ scriptname packagename.deb packaganame.tce


TMP1="`mktemp -d /tmp/tce.1.XXXXXX`"
TMP2="$TMP1"/pkg
FILE="$1"
APPNAME="$2"
INPUT=${FILE##*.}

make_tce() {
	mkdir "$TMP2"
	ar p "$FILE" data.tar.gz > "$TMP1"/data.tar.gz
	tar xzvf "$TMP1"/data.tar.gz -C "$TMP2"
	cd "$TMP2"
	[ -d usr/share/doc ] && rm -r usr/share/doc
	[ -d usr/share/man ] && rm -r usr/share/man
	[ -d usr/share/menu ] && rm -r usr/share/menu
	find . -type d -empty | xargs rmdir > /dev/null 2&>1
	find `ls` -not -type d > "$TMP1"/list
	tar -T "$TMP1"/list -czvf /home/"$USER"/"$APPNAME"
	cd
	rm -r "$TMP1"
}

make_tcz() {
	mkdir "$TMP2"
	ar p "$FILE" data.tar.gz > "$TMP1"/data.tar.gz
	tar xzvf "$TMP1"/data.tar.gz -C "$TMP2"
	cd "$TMP2"
	[ -d usr/share/doc ] && rm -r usr/share/doc
	[ -d usr/share/man ] && rm -r usr/share/man
	[ -d usr/share/menu ] && rm -r usr/share/menu
	find . -type d -empty | xargs rmdir > /dev/null 2&>1
	mksquashfs "$TMP2" /home/"$USER"/"$APPNAME"
	cd
	rm -r "$TMP1"
}

[ "$USER" == "root" ] && echo "Do not run as root." && exit 1
[ -z "$APPNAME" ] && echo "You must specify an extension name." && exit 1
[ -f /home/"$USER"/"$APPNAME" ] && echo "You have an existing extension in your \
home directory, you need to move or delete it before trying again." && exit 1
[ -z "$1" ] && echo "You must specify a file."
if [ ! "$INPUT" == "deb" ] ; then
	echo "Only Debian packages work with this."
	exit 1
fi
EXT=${APPNAME##*.}
if [ `echo "$EXT" | grep "tce"` 2>/dev/null ]; then
	make_tce
elif [ `echo "$EXT" | grep "tcz"` 2>/dev/null ]; then
	make_tcz
else 	
	echo "You need to specify either a tcz or tce for the output file."
	exit 1
fi
	
if [ -f /home/"$USER"/"$APPNAME" ]; then
	echo "Success."
else
	echo "Something went wrong."
fi
